# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 949)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(440, 740, 271, 51))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.groupBox_OtherSettings = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_OtherSettings.setGeometry(QtCore.QRect(730, 280, 381, 231))
        self.groupBox_OtherSettings.setObjectName("groupBox_OtherSettings")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_OtherSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 362, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_AddTimeDateToScreen = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_AddTimeDateToScreen.setObjectName("checkBox_AddTimeDateToScreen")
        self.verticalLayout.addWidget(self.checkBox_AddTimeDateToScreen)
        self.checkBox_OpenFolder = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_OpenFolder.setObjectName("checkBox_OpenFolder")
        self.verticalLayout.addWidget(self.checkBox_OpenFolder)
        self.checkBox_OpenExcelFile = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_OpenExcelFile.setObjectName("checkBox_OpenExcelFile")
        self.verticalLayout.addWidget(self.checkBox_OpenExcelFile)
        self.checkBox_NoLimits = QtWidgets.QCheckBox(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.checkBox_NoLimits.setPalette(palette)
        self.checkBox_NoLimits.setObjectName("checkBox_NoLimits")
        self.verticalLayout.addWidget(self.checkBox_NoLimits)
        self.groupBox_Cutters = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Cutters.setGeometry(QtCore.QRect(730, 140, 231, 121))
        self.groupBox_Cutters.setObjectName("groupBox_Cutters")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_Cutters)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 210, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_Windowscreen = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_Windowscreen.setObjectName("radioButton_Windowscreen")
        self.verticalLayout_3.addWidget(self.radioButton_Windowscreen)
        self.radioButton_Fullscreen = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_Fullscreen.setObjectName("radioButton_Fullscreen")
        self.verticalLayout_3.addWidget(self.radioButton_Fullscreen)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 341, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_SitesAddresses = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_SitesAddresses.setGeometry(QtCore.QRect(10, 20, 321, 351))
        self.textEdit_SitesAddresses.setObjectName("textEdit_SitesAddresses")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 381))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_Requests = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_Requests.setGeometry(QtCore.QRect(10, 20, 321, 351))
        self.textEdit_Requests.setObjectName("textEdit_Requests")
        self.groupBox_Searches = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Searches.setGeometry(QtCore.QRect(730, 10, 171, 111))
        self.groupBox_Searches.setObjectName("groupBox_Searches")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_Searches)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 144, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_Yandex = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_Yandex.setObjectName("checkBox_Yandex")
        self.verticalLayout_2.addWidget(self.checkBox_Yandex)
        self.checkBox_Google = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_Google.setObjectName("checkBox_Google")
        self.verticalLayout_2.addWidget(self.checkBox_Google)
        self.groupBox_SavePath = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_SavePath.setGeometry(QtCore.QRect(10, 630, 701, 101))
        self.groupBox_SavePath.setObjectName("groupBox_SavePath")
        self.label_SavePath = QtWidgets.QLabel(self.groupBox_SavePath)
        self.label_SavePath.setGeometry(QtCore.QRect(10, 60, 671, 31))
        self.label_SavePath.setObjectName("label_SavePath")
        self.pushButton_SavePath = QtWidgets.QPushButton(self.groupBox_SavePath)
        self.pushButton_SavePath.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.pushButton_SavePath.setObjectName("pushButton_SavePath")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 701, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 681, 191))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(325)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.label_Info = QtWidgets.QLabel(self.centralwidget)
        self.label_Info.setGeometry(QtCore.QRect(210, 810, 721, 41))
        self.label_Info.setLineWidth(4)
        self.label_Info.setTextFormat(QtCore.Qt.PlainText)
        self.label_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Info.setObjectName("label_Info")
        self.pushButton_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(720, 740, 271, 51))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AdsHunter Alpha v0.4"))
        self.pushButton_Start.setText(_translate("MainWindow", "Начать"))
        self.groupBox_OtherSettings.setTitle(_translate("MainWindow", "Другие настройки"))
        self.checkBox_AddTimeDateToScreen.setText(_translate("MainWindow", "Добавить дату и время на скрин"))
        self.checkBox_OpenFolder.setText(_translate("MainWindow", "Открыть папку при завершении поиска"))
        self.checkBox_OpenExcelFile.setText(_translate("MainWindow", "Открыть Excel файл при завершении поиска"))
        self.checkBox_NoLimits.setText(_translate("MainWindow", "Без огрничений на кол-во запросов"))
        self.groupBox_Cutters.setTitle(_translate("MainWindow", "Варианты скриншотов"))
        self.radioButton_Windowscreen.setText(_translate("MainWindow", "Windowscreen mode"))
        self.radioButton_Fullscreen.setText(_translate("MainWindow", "Fullscreen"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Сайты"))
        self.groupBox.setTitle(_translate("MainWindow", "Запросы"))
        self.groupBox_Searches.setTitle(_translate("MainWindow", "Системы поиска"))
        self.checkBox_Yandex.setText(_translate("MainWindow", "Яндекс"))
        self.checkBox_Google.setText(_translate("MainWindow", "Google"))
        self.groupBox_SavePath.setTitle(_translate("MainWindow", "Путь для сохранения"))
        self.label_SavePath.setText(_translate("MainWindow", "Путь: "))
        self.pushButton_SavePath.setText(_translate("MainWindow", "Выбрать путь для сохранения"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Регионы для поиска"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Регион"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "lr="))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_Info.setText(_translate("MainWindow", "test"))
        self.pushButton_Cancel.setText(_translate("MainWindow", "Отмена"))
